spring:
  application:
    name: Wishlist
  data:
    mongodb:
      database: wishlist
      username: root
      password: root
      authentication-database: admin
      auto-index-creation: true
wishlist:
  items:
    max-size: ${WISHLIST_ITEMS_MAX_SIZE:20}